services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  springboot:
    build:
      context: .  # Thư mục hiện tại (cùng cấp với Dockerfile)
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - DATABASE_URL= ${{ secrets.DATABASE_URL }}
      - DATABASE_USERNAME= ${{ secrets.DATABASE_USERNAME }}
      - DATABASE_PASSWORD= ${{ secrets.DATABASE_PASSWORD }}
      - MAIL_USERNAME= ${{ secrets.MAIL_USERNAME }}
      - MAIL_PASSWORD= ${{ secrets.MAIL_PASSWORD }}
      - JWT_SIGNERKEY= ${{ secrets.JWT_SIGNERKEY }}
      - JWT_VALID_DURATION= ${{ secrets.JWT_VALID_DURATION }}
      - JWT_REFRESH= ${{ secrets.JWT_REFRESH }}
      - CLOUD_NAME= ${{ secrets.CLOUD_NAME }}
      - API_KEY= ${{ secrets.API_KEY }}
      - API_SECRET= ${{ secrets.API_SECRET }}