spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://auction-db.cv0uw4swopxz.ap-southeast-1.rds.amazonaws.com/g_auction}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:BGTgkglFarU3eXj}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  mail :
    host : smtp.gmail.com
    port : 587
    username : ${MAIL_USERNAME:dinhmanhbh03@gmail.com}
    password : ${MAIL_PASSWORD:hchj rjca tpzg kwpn}
    properties:
      mail:
        smtp:
          auth : true
          starttls:
            enable : true
#          connectiontimeout : 100
#          timeout : 100
#          writetimeout : 100
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      ssl:
        enabled: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore:
        driverDelegateClass : org.quartz.impl.jdbcjobstore.StdJDBCDelegate

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: ${JWT_VALID_DURATION:300}
  refreshable-duration: ${JWT_REFRESH:3600}

server:
  port: 8080
  servlet:
    context-path: /auction
    
websocket:
  endpoint: /ws

cloudinary:
  name: ${CLOUD_NAME:dorl0yxpe}
  key: ${API_KEY:999929732961462}
  secret: ${API_SECRET:DDuOOlQ5ewAOkgRjR5E1GawxXqc}

alloworigins: http://localhost:3000